### ISSUE TITLE
"Explain Model" under the Explain widget  is not available in the version 3.35.0

### ISSUE THREAD

**Issue by neefra** [biolab/orange3-explain#65]
Dear Team, 

I can't see the **Explain Model** option in the Explain widget 

There are only two options available. 

**Feature Importance 
ICE.** 

Please guide.

**Comment by PrimozGodec** [comment]
Thank you for the report, but we need more information to help you. Can you please fill in the information requested by the issue template?


- Operating system:
- Orange version:
- How you installed Orange:

**Comment by neefra** [comment]
Operating system: Window 10 Enterprise
Orange version: 3.35.0
How you installed Orange: Download the application from the Orange Website.

**Comment by PrimozGodec** [comment]
Can you try one more thing? Open Orange, go to `View>Log` (on the top window row menu) and if you see any error there can you paste them into this issue? If the log includes any sensitive paths on your computer you can shorten them.

**Comment by neefra** [comment]
C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangewidget\gui.py:2068: UserWarning: decorate OWLogisticRegression.apply with @gui.deferred and then explicitly call apply.now or apply.deferred.
  warnings.warn(
C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangewidget\gui.py:2068: UserWarning: decorate OWPermutationImportance.commit with @gui.deferred and then explicitly call commit.now or commit.deferred.
  warnings.warn(
C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangewidget\gui.py:2068: UserWarning: decorate OWRandomForest.apply with @gui.deferred and then explicitly call apply.now or apply.deferred.
  warnings.warn(
C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\explain\widgets\owice.py:264: OrangeDeprecationWarning: Call to deprecated <function Table.get_column_view at 0x000001D5B5B18820>; Instead, use Table.get_column (or Table.set_column if you must)
  x_data = self.__data.get_column_view(self.__feature)[0][indices]
C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\explain\widgets\owice.py:264: OrangeDeprecationWarning: Call to deprecated <function Table.get_column_view at 0x000001D5B5B18820>; Instead, use Table.get_column (or Table.set_column if you must)
  x_data = self.__data.get_column_view(self.__feature)[0][indices]
C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\explain\widgets\owice.py:264: OrangeDeprecationWarning: Call to deprecated <function Table.get_column_view at 0x000001D5B5B18820>; Instead, use Table.get_column (or Table.set_column if you must)
  x_data = self.__data.get_column_view(self.__feature)[0][indices]
C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\explain\widgets\owice.py:264: OrangeDeprecationWarning: Call to deprecated <function Table.get_column_view at 0x000001D5B5B18820>; Instead, use Table.get_column (or Table.set_column if you must)
  x_data = self.__data.get_column_view(self.__feature)[0][indices]

**Comment by PrimozGodec** [comment]
@neefra, thank you for the log. Strangely, the log doesn't show the error behind missing widgets. Can you do one more thing:
1. Open the Orange command prompt. You find it if you press the start windows button and then type the Orange command prompt.
2. Run the command `orange-canvas -l 5`
3. Copy and paste everything you see in the log after running this command.

**Comment by neefra** [comment]
2023-09-01 10:49:58,796:DEBUG:orangecanvas.main: Loading paths from argv: 
2023-09-01 10:49:58,811:DEBUG:orangecanvas.registry.cache: Loading widget registry cache ('C:/Users/rmhimqu/AppData/Local/Orange/cache\\3.35.0\\registry-cache.pck').
2023-09-01 10:49:59,370:INFO:orangecanvas.registry.base: A category with 'Data' name already exists
2023-09-01 10:49:59,402:INFO:orangecanvas.registry.base: A category with 'Visualize' name already exists
2023-09-01 10:49:59,407:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\rmhimqu\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\Orange\\widgets\\visualize\\owscatterplotgraph.py'.
2023-09-01 10:49:59,407:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\rmhimqu\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\Orange\\widgets\\visualize\\owtreeviewer2d.py'.
2023-09-01 10:49:59,407:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\rmhimqu\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\Orange\\widgets\\visualize\\pythagorastreeviewer.py'.
2023-09-01 10:49:59,407:INFO:orangecanvas.registry.base: A category with 'Model' name already exists
2023-09-01 10:49:59,425:INFO:orangecanvas.registry.base: A category with 'Evaluate' name already exists
2023-09-01 10:49:59,425:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\rmhimqu\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\Orange\\widgets\\evaluate\\contexthandlers.py'.
2023-09-01 10:49:59,425:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\rmhimqu\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\Orange\\widgets\\evaluate\\utils.py'.
2023-09-01 10:49:59,425:INFO:orangecanvas.registry.base: A category with 'Unsupervised' name already exists
2023-09-01 10:49:59,452:DEBUG:sql_log: Logging started: 2023-09-01 10:49:59
2023-09-01 10:50:00,343:INFO:orangecanvas.registry.discovery: Could not import 'orangecontrib.bioinformatics.widgets.OWGenialisExpressions'.
Traceback (most recent call last):
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 307, in iter_widget_descriptions
    module = asmodule(name)
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 550, in asmodule
    return __import__(module, fromlist=[""])
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\bioinformatics\widgets\OWGenialisExpressions.py", line 9, in <module>
    import resdk.tables
ModuleNotFoundError: No module named 'resdk'
2023-09-01 10:50:00,363:INFO:orangecanvas.registry.discovery: Could not import 'orangecontrib.bioinformatics.widgets.OWSingleSampleScoring'.
Traceback (most recent call last):
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 307, in iter_widget_descriptions
    module = asmodule(name)
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 550, in asmodule
    return __import__(module, fromlist=[""])
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\bioinformatics\widgets\OWSingleSampleScoring.py", line 5, in <module>
    from single_sample_gsea import ss_gsea
ModuleNotFoundError: No module named 'single_sample_gsea'
2023-09-01 10:50:01,296:INFO:orangecanvas.registry.discovery: Could not import 'orangecontrib.bioinformatics.widgets.OWdictyExpress'.
Traceback (most recent call last):
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 307, in iter_widget_descriptions
    module = asmodule(name)
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 550, in asmodule
    return __import__(module, fromlist=[""])
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\bioinformatics\widgets\OWdictyExpress.py", line 16, in <module>
    from orangecontrib.bioinformatics import resolwe
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\bioinformatics\resolwe\__init__.py", line 4, in <module>
    from .resapi import ResolweAPI
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\bioinformatics\resolwe\resapi.py", line 6, in <module>
    from resdk import Resolwe
ModuleNotFoundError: No module named 'resdk'
2023-09-01 10:50:01,342:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\rmhimqu\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecontrib\\explain\\widgets\\owexplainfeaturebase.py'.
2023-09-01 10:50:03,343:WARNING:orangecanvas.registry.discovery: Error while importing 'orangecontrib.explain.widgets.owexplainmodel'.
Traceback (most recent call last):
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 307, in iter_widget_descriptions
    module = asmodule(name)
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 550, in asmodule
    return __import__(module, fromlist=[""])
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\explain\widgets\owexplainmodel.py", line 26, in <module>
    from orangecontrib.explain.explainer import \
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\explain\explainer.py", line 6, in <module>
    from shap import KernelExplainer, TreeExplainer
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\shap\__init__.py", line 5, in <module>
    from ._explanation import Explanation, Cohorts
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\shap\_explanation.py", line 13, in <module>
    from .utils._exceptions import DimensionError
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\shap\utils\__init__.py", line 1, in <module>
    from ._clustering import (
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\shap\utils\_clustering.py", line 7, in <module>
    from numba import njit
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\numba\__init__.py", line 43, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
2023-09-01 10:50:03,454:WARNING:orangecanvas.registry.discovery: Error while importing 'orangecontrib.explain.widgets.owexplainprediction'.
Traceback (most recent call last):
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 307, in iter_widget_descriptions
    module = asmodule(name)
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 550, in asmodule
    return __import__(module, fromlist=[""])
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\explain\widgets\owexplainprediction.py", line 28, in <module>
    from orangecontrib.explain.explainer import RGB_LOW, RGB_HIGH, \
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\explain\explainer.py", line 6, in <module>
    from shap import KernelExplainer, TreeExplainer
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\shap\__init__.py", line 5, in <module>
    from ._explanation import Explanation, Cohorts
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\shap\_explanation.py", line 13, in <module>
    from .utils._exceptions import DimensionError
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\shap\utils\__init__.py", line 1, in <module>
    from ._clustering import (
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\shap\utils\_clustering.py", line 7, in <module>
    from numba import njit
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\numba\__init__.py", line 43, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
2023-09-01 10:50:03,499:WARNING:orangecanvas.registry.discovery: Error while importing 'orangecontrib.explain.widgets.owexplainpredictions'.
Traceback (most recent call last):
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 307, in iter_widget_descriptions
    module = asmodule(name)
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 550, in asmodule
    return __import__(module, fromlist=[""])
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\explain\widgets\owexplainpredictions.py", line 36, in <module>
    from orangecontrib.explain.explainer import explain_predictions, \
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\explain\explainer.py", line 6, in <module>
    from shap import KernelExplainer, TreeExplainer
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\shap\__init__.py", line 5, in <module>
    from ._explanation import Explanation, Cohorts
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\shap\_explanation.py", line 13, in <module>
    from .utils._exceptions import DimensionError
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\shap\utils\__init__.py", line 1, in <module>
    from ._clustering import (
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\shap\utils\_clustering.py", line 7, in <module>
    from numba import njit
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\numba\__init__.py", line 43, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
2023-09-01 10:50:03,515:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\rmhimqu\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecontrib\\geo\\widgets\\plotutils.py'.
2023-09-01 10:50:03,546:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\rmhimqu\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecontrib\\network\\widgets\\graphview.py'.
2023-09-01 10:50:03,561:INFO:orangecanvas.registry.discovery: Could not import 'orangecontrib.prototypes.widgets.owdfdisplay'.
Traceback (most recent call last):
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 307, in iter_widget_descriptions
    module = asmodule(name)
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 550, in asmodule
    return __import__(module, fromlist=[""])
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\prototypes\widgets\owdfdisplay.py", line 41, in <module>
    from Orange.widgets.data.owtable import BlockSelectionModel
ImportError: cannot import name 'BlockSelectionModel' from 'Orange.widgets.data.owtable' (C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\Orange\widgets\data\owtable.py)
2023-09-01 10:50:03,577:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\rmhimqu\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecontrib\\single_cell\\widgets\\contingency_table.py'.
2023-09-01 10:50:03,733:WARNING:orangecanvas.registry.discovery: Error while importing 'orangecontrib.single_cell.widgets.load_data'.
Traceback (most recent call last):
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 307, in iter_widget_descriptions
    module = asmodule(name)
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 550, in asmodule
    return __import__(module, fromlist=[""])
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\single_cell\widgets\load_data.py", line 10, in <module>
    import loompy as lp
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\loompy\__init__.py", line 11, in <module>
    from .loompy import connect, create, create_append, combine, create_from_cellranger, LoomConnection, new, combine_faster, create_from_matrix_market
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\loompy\loompy.py", line 33, in <module>
    import numpy_groupies.aggregate_numpy as npg
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\numpy_groupies\__init__.py", line 47, in <module>
    import numba
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\numba\__init__.py", line 43, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
2023-09-01 10:50:03,812:WARNING:orangecanvas.registry.discovery: Error while importing 'orangecontrib.single_cell.widgets.owloaddata'.
Traceback (most recent call last):
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 307, in iter_widget_descriptions
    module = asmodule(name)
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 550, in asmodule
    return __import__(module, fromlist=[""])
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\single_cell\widgets\owloaddata.py", line 23, in <module>
    from orangecontrib.single_cell.widgets.load_data import get_data_loader, Loader
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\single_cell\widgets\load_data.py", line 10, in <module>
    import loompy as lp
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\loompy\__init__.py", line 11, in <module>
    from .loompy import connect, create, create_append, combine, create_from_cellranger, LoomConnection, new, combine_faster, create_from_matrix_market
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\loompy\loompy.py", line 33, in <module>
    import numpy_groupies.aggregate_numpy as npg
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\numpy_groupies\__init__.py", line 47, in <module>
    import numba
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\numba\__init__.py", line 43, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
2023-09-01 10:50:03,827:WARNING:orangecanvas.registry.discovery: Error while importing 'orangecontrib.single_cell.widgets.owmultisample'.
Traceback (most recent call last):
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 307, in iter_widget_descriptions
    module = asmodule(name)
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 550, in asmodule
    return __import__(module, fromlist=[""])
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\single_cell\widgets\owmultisample.py", line 21, in <module>
    from orangecontrib.single_cell.widgets.load_data import Concatenate, Loader
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\single_cell\widgets\load_data.py", line 10, in <module>
    import loompy as lp
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\loompy\__init__.py", line 11, in <module>
    from .loompy import connect, create, create_append, combine, create_from_cellranger, LoomConnection, new, combine_faster, create_from_matrix_market
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\loompy\loompy.py", line 33, in <module>
    import numpy_groupies.aggregate_numpy as npg
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\numpy_groupies\__init__.py", line 47, in <module>
    import numba
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\numba\__init__.py", line 43, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "C:\Users\rmhimqu\AppData\Local\Programs\Orange\lib\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
2023-09-01 10:50:04,092:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\rmhimqu\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecontrib\\survival_analysis\\widgets\\data.py'.
2023-09-01 10:50:05,094:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\rmhimqu\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\_textable\\widgets\\TextableUtils.py'.
2023-09-01 10:50:06,327:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\rmhimqu\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecontrib\\timeseries\\widgets\\_owmodel.py'.
2023-09-01 10:50:06,327:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\rmhimqu\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecontrib\\timeseries\\widgets\\_rangeslider.py'.
2023-09-01 10:50:06,327:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\rmhimqu\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecontrib\\timeseries\\widgets\\owperiodbase.py'.
2023-09-01 10:50:06,343:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\rmhimqu\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecontrib\\timeseries\\widgets\\utils.py'.
2023-09-01 10:50:06,428:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\rmhimqu\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecontrib\\spectroscopy\\widgets\\gui.py'.
2023-09-01 10:50:06,429:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\rmhimqu\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecontrib\\spectroscopy\\widgets\\line_geometry.py'.
2023-09-01 10:50:06,438:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\rmhimqu\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecontrib\\spectroscopy\\widgets\\peak_editors.py'.
2023-09-01 10:50:06,439:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\rmhimqu\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecontrib\\spectroscopy\\widgets\\peakfit_compute.py'.
2023-09-01 10:50:06,440:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\rmhimqu\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecontrib\\spectroscopy\\widgets\\utils.py'.
2023-09-01 10:50:06,440:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\rmhimqu\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecontrib\\spectroscopy\\widgets\\visual_settings.py'.
2023-09-01 10:50:06,441:DEBUG:orangecanvas.registry.cache: Saving widget registry cache with 269 entries ('C:/Users/rmhimqu/AppData/Local/Orange/cache\\3.35.0\\registry-cache.pck').
2023-09-01 10:50:06,453:DEBUG:orangecanvas.registry: 'set_global_registry()' - setting registry.
2023-09-01 10:50:06,469:INFO:orangecanvas.main: Adding search path 'C:\\Users\\rmhimqu\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecanvas\\styles\\orange' for prefix, 'canvas_icons'
2023-09-01 10:50:06,561:DEBUG:orangewidget.workflow.widgetsscheme: Scheme node properties sync (changed: False)
2023-09-01 10:50:06,595:DEBUG:orangecanvas.gui.stackedwidget: Stack transition start ()
2023-09-01 10:50:06,595:DEBUG:orangecanvas.gui.stackedwidget: Stack transition finished ()

**Comment by neefra** [comment]
Any update?

**Comment by PrimozGodec** [comment]
Sorry for a bit of delay. The error you are getting is strange (some unexplained Numba errors). I just tried to install fresh version of Orange on my Windows computer and then to install the add-on, and it looks ok. 

Something may not have installed well for you (maybe some permission errors on your computer) -- I also see some `ModuleNotFoundError` for bioinformatics add-on in your log.

Maybe the best solution would be to reinstall Orange completely:
1. Uninstall the current Orange from your computer (in add or remove programs Windows settings). 
2. Also, manually remove the `Orange` folder from your computer (to eliminate traces). The folder might be in `C:\Users\<your username>\AppData\Local\Programs` if you installed just for yourself or in `C:\Program Files\` if you installed Orange for all users.
3. Install Orange with the installer from the website again. Since it might be that you had problems with permissions while installing addons, I would suggest selecting `Install just for me` option when installing Orange.
